CREATE TABLE [dbo].[UrjanetStatements]
(
	[Logical Account Id] NVARCHAR(100) not null, 
    [Account Type] NVARCHAR(20) NULL, 
    [Normalized Account Number] NVARCHAR(20) NULL, 
    [Raw Account Number] NVARCHAR(20) NULL, 
    [Utility Provider Id] NVARCHAR(100) NULL, 
    [Provider Name] NVARCHAR(200) NULL, 
    [Summary Account Number] NVARCHAR(100) NULL, 
    [Statement Id] NVARCHAR(100) NULL, 
    [Invoice Number] NVARCHAR(100) NULL, 
    [Statement Type] NVARCHAR(20) NULL, 
    [Statement Date] DATETIME NULL, 
    [Due Date] DATETIME NULL, 
    [Start Date] DATETIME NULL, 
    [End Date] DATETIME NULL, 
    [Service Recipient Name] NVARCHAR(500) NULL, 
    [Service Street] NVARCHAR(200) NULL, 
    [Service Street 2] NVARCHAR(200) NULL, 
    [Service City] NVARCHAR(100) NULL, 
    [Service State] NVARCHAR(10) NULL, 
    [Service Zip Code] NVARCHAR(50) NULL, 
    [Raw Service Address] NVARCHAR(200) NULL, 
    [Billing Recipient Name] NVARCHAR(200) NULL, 
    [Billing Street] NVARCHAR(200) NULL, 
    [Billing Street 2] NVARCHAR(200) NULL, 
    [Billing City] NVARCHAR(100) NULL, 
    [Billing State] NVARCHAR(10) NULL, 
    [Billing Zip Code] NVARCHAR(50) NULL, 
    [Raw Billing Address] NVARCHAR(500) NULL, 
    [Payment Recipient Name] NVARCHAR(200) NULL, 
    [Payment Street] NVARCHAR(200) NULL, 
    [Payment Street 2] NVARCHAR(200) NULL, 
    [Payment City] NVARCHAR(100) NULL, 
    [Payment State] NVARCHAR(10) NULL, 
    [Payment Zip Code] NVARCHAR(50) NULL, 
    [Raw Payment Address] NVARCHAR(500) NULL, 
    [Total Due] NVARCHAR(50) NULL, 
    [Outstanding Balance] NVARCHAR(50) NULL, 
    [Current Charges] NVARCHAR(50) NULL, 
    [Previous Charges] NVARCHAR(50) NULL, 
    [Payment Currency] NVARCHAR(50) NULL, 
    [Correlation Id] NVARCHAR(50) NULL, 
    [PropertyID] NVARCHAR(50) NULL
)
